language: python
python:
- "3.7"
if: type = push
script:
- pip3 install --upgrade setuptools pip
- pip3 install yamllint
- yamllint docassemble/law/data/questions
deploy:
  provider: pypi
  user: "$PYPI_USER"
  password: "$PYPI_SECRET"
