on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@master
    - name: Setup and Deploy
      run: |
        pip3 install twine
        twine upload -u $PYPI_USER -p $PYPI_PASSWORD *
      env:
        PYPI_USER: ${{ secrets.PYPI_USER }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
