on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@master
    - name: Setup and Test
      run: |
        pip3 install yamllint
        sed -i $'s/\t/  /g' docassemble/law/data/questions/*.yml
        yamllint docassemble/law/data/questions
